services:
  - type: web
    name: external-brain
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -b 0.0.0.0:10000
